modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

logoFile="assets/wildernessquesting.png"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="SamIr0n"

description='''
Wilderness Questing is a flexible, data-driven quest framework built for modpack creators and developers. Create branching quest lines with configurable objectives, requirements, conditions, and rewards using JSON. The mod provides the framework and quest book without imposing a predefined quest line, leaving every pack free to create its own adventure.
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"